// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/articleDataModel.dart';
import 'data/models/audioDataModel.dart';
import 'data/models/bookDataModel.dart';
import 'data/models/categoryDataModel.dart';
import 'data/models/creatorDataModel.dart';
import 'data/models/partDataModel.dart';
import 'data/models/personDataModel.dart';
import 'data/models/tagDataModel.dart';
import 'data/models/videoDataModel.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 394699857501310013),
    name: 'CategoryDataModel',
    lastPropertyId: const obx_int.IdUid(8, 8914295541855306743),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3495302254030092973),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6776484871021674121),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5052953887121577006),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8985748480727615732),
        name: 'imgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 9179150149946913473),
        name: 'isFor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5129874300583038544),
        name: 'isActive',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7150062822835738211),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8914295541855306743),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2963559256900539031),
    name: 'CreatorDataModel',
    lastPropertyId: const obx_int.IdUid(10, 9103388985536045611),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6747086668630494749),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 569299337252760771),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1344781948024257419),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4755759996938574308),
        name: 'imgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 618788915784822147),
        name: 'instaLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4522659034617642585),
        name: 'xLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6392112751105580879),
        name: 'wikiLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7016763478872891787),
        name: 'isFor',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 9074800768140484538),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 9103388985536045611),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 3251236955509698794),
    name: 'PartDataModel',
    lastPropertyId: const obx_int.IdUid(8, 2983333713680234383),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4267173381798318236),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4281304185443880794),
        name: 'from',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8583925796075652421),
        name: 'to',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4343678538985289893),
        name: 'sortNumber',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1895611110898418205),
        name: 'unit',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8835058252008345245),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2381409106115679322),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2983333713680234383),
        name: 'doneAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 8563456502839054976),
    name: 'PersonDataModel',
    lastPropertyId: const obx_int.IdUid(9, 5671871003420121864),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2184509048685118264),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2221351701027784755),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1794949890673217430),
        name: 'imgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1678213538621388113),
        name: 'contactInfo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6486322879855154887),
        name: 'phoneNumber',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3229948219228510807),
        name: 'telegramId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8275578346751422302),
        name: 'whatsAppId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3843725337216894015),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5671871003420121864),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 8219558637018139414),
    name: 'TagDataModel',
    lastPropertyId: const obx_int.IdUid(6, 8226747969189907355),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1219063240839901825),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5179337440300845980),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9060803083535220906),
        name: 'emoji',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 344576106002991929),
        name: 'color',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2832462171306449539),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8226747969189907355),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 5286136240034329428),
    name: 'AudioDataModel',
    lastPropertyId: const obx_int.IdUid(13, 6808098385261951466),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5861269937207469401),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4480598913423517786),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2027315003292595633),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6681084087819257349),
        name: 'srcLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4724269269208033667),
        name: 'imgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4330461594355769129),
        name: 'state',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2091177118209518777),
        name: 'myStarCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1989293030817632443),
        name: 'starCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4415690396468911159),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 391532923016217868),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5574577239921535255),
        name: 'hostId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(4, 1937502100261002669),
        relationField: 'host',
        relationTarget: 'CreatorDataModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 558324595434012927),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(5, 4946800383141316696),
        relationField: 'category',
        relationTarget: 'CategoryDataModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 6808098385261951466),
        name: 'tagId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(6, 3304799451364227667),
        relationField: 'tag',
        relationTarget: 'TagDataModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(3, 8304152908870740824),
        name: 'episodes',
        targetId: const obx_int.IdUid(7, 5286136240034329428),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(4, 6983520069188337809),
        name: 'allParts',
        targetId: const obx_int.IdUid(3, 3251236955509698794),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(8, 5694658342765565866),
    name: 'BookDataModel',
    lastPropertyId: const obx_int.IdUid(17, 7158409865120385891),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8417664488561395838),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5283826302661221782),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 437513682966012259),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8333074922342331181),
        name: 'srcLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5409963458688862277),
        name: 'reviewLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6711114229543172805),
        name: 'imgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5846106253902698866),
        name: 'state',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3592352313328393368),
        name: 'kind',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6183793052729732017),
        name: 'myStarCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 6218870142672647785),
        name: 'starCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 972868837489144767),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 2008686192297377037),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8400708427439553117),
        name: 'authorId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 8065305968451273887),
        relationField: 'author',
        relationTarget: 'CreatorDataModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 4098521868773800094),
        name: 'lenderId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(8, 2850051100099495333),
        relationField: 'lender',
        relationTarget: 'PersonDataModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7403807839197673996),
        name: 'borrowerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(9, 1155161260340527381),
        relationField: 'borrower',
        relationTarget: 'PersonDataModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7498905537451762560),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(10, 2506780225479292291),
        relationField: 'category',
        relationTarget: 'CategoryDataModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 7158409865120385891),
        name: 'tagId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(11, 1935215569675672471),
        relationField: 'tag',
        relationTarget: 'TagDataModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(5, 677498402874620847),
        name: 'series',
        targetId: const obx_int.IdUid(8, 5694658342765565866),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(6, 7759913245870567056),
        name: 'allParts',
        targetId: const obx_int.IdUid(3, 3251236955509698794),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 478562498836310008),
    name: 'ArticleDataModel',
    lastPropertyId: const obx_int.IdUid(13, 3411297636181770408),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7431602400757044434),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7052571121158526410),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4910032366751117954),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7112113625671260432),
        name: 'srcLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6734470574020520109),
        name: 'imgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4040190259216089819),
        name: 'state',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4771126850330317634),
        name: 'myStarCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3845064689816600490),
        name: 'starCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 8767806865116475984),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8681426025729827462),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 8734203818024645193),
        name: 'writerId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(1, 3744404352988232452),
        relationField: 'writer',
        relationTarget: 'CreatorDataModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7623377289399611948),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 1249351784769552626),
        relationField: 'category',
        relationTarget: 'CategoryDataModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 3411297636181770408),
        name: 'tagId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(3, 5150016324923097994),
        relationField: 'tag',
        relationTarget: 'TagDataModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 5871466929430192744),
        name: 'subArticles',
        targetId: const obx_int.IdUid(10, 478562498836310008),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 7927065451573185424),
        name: 'allParts',
        targetId: const obx_int.IdUid(3, 3251236955509698794),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(11, 908369626461378473),
    name: 'VideoDataModel',
    lastPropertyId: const obx_int.IdUid(15, 7244409427896391841),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 329647919243878905),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4899222852244447282),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3025269010688831697),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9124366214525585420),
        name: 'imgPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2527967772755221789),
        name: 'srcLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5959262128590980146),
        name: 'reviewLink',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6865843561512030498),
        name: 'state',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 4873807220167246820),
        name: 'kind',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 388645254597586452),
        name: 'myStarCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8924766127320584549),
        name: 'starCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5968201371233910265),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 7751691272071129293),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8816888996022932593),
        name: 'authorId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(12, 594326089344902940),
        relationField: 'author',
        relationTarget: 'CreatorDataModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 1285703126122845730),
        name: 'categoryId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(13, 5244514079228160144),
        relationField: 'category',
        relationTarget: 'CategoryDataModel',
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7244409427896391841),
        name: 'tagId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(14, 8341239411223296513),
        relationField: 'tag',
        relationTarget: 'TagDataModel',
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(7, 8938418616669260303),
        name: 'seasons',
        targetId: const obx_int.IdUid(11, 908369626461378473),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(8, 2039573190397485539),
        name: 'episodes',
        targetId: const obx_int.IdUid(11, 908369626461378473),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(11, 908369626461378473),
    lastIndexId: const obx_int.IdUid(14, 8341239411223296513),
    lastRelationId: const obx_int.IdUid(8, 2039573190397485539),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [2044285761471285534, 6224410449028813634],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      3498658896946705679,
      1954070924638462855,
      8661280354965377807,
      8767297579622262511,
      379286010199157575,
      6083760043070518001,
      5658988105738898346,
      4982674673124835189,
      3116576052399373056,
      6821201640273568453,
      9216200932509814536,
      7962431734031239225,
      7967438194914752966,
      7428050321913237974,
      8615475513764022440,
      4035360786061675499,
      7255762665248923000,
      3992501871832894829,
      3864863310251401956,
      6163917219428685748,
      6635609490872363580,
      1960496101390936671,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CategoryDataModel: obx_int.EntityDefinition<CategoryDataModel>(
      model: _entities[0],
      toOneRelations: (CategoryDataModel object) => [],
      toManyRelations: (CategoryDataModel object) => {},
      getId: (CategoryDataModel object) => object.id,
      setId: (CategoryDataModel object, int id) {
        object.id = id;
      },
      objectToFB: (CategoryDataModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final imgPathOffset = fbb.writeString(object.imgPath);
        final isForOffset = fbb.writeString(object.isFor);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, imgPathOffset);
        fbb.addOffset(4, isForOffset);
        fbb.addBool(5, object.isActive);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CategoryDataModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..imgPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..isFor = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..isActive = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            14,
            false,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          );

        return object;
      },
    ),
    CreatorDataModel: obx_int.EntityDefinition<CreatorDataModel>(
      model: _entities[1],
      toOneRelations: (CreatorDataModel object) => [],
      toManyRelations: (CreatorDataModel object) => {},
      getId: (CreatorDataModel object) => object.id,
      setId: (CreatorDataModel object, int id) {
        object.id = id;
      },
      objectToFB: (CreatorDataModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final imgPathOffset = fbb.writeString(object.imgPath);
        final instaLinkOffset = fbb.writeString(object.instaLink);
        final xLinkOffset = fbb.writeString(object.xLink);
        final wikiLinkOffset = fbb.writeString(object.wikiLink);
        final isForOffset = fbb.writeString(object.isFor);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, imgPathOffset);
        fbb.addOffset(4, instaLinkOffset);
        fbb.addOffset(5, xLinkOffset);
        fbb.addOffset(6, wikiLinkOffset);
        fbb.addOffset(7, isForOffset);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CreatorDataModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..imgPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..instaLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..xLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..wikiLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..isFor = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
          );

        return object;
      },
    ),
    PartDataModel: obx_int.EntityDefinition<PartDataModel>(
      model: _entities[2],
      toOneRelations: (PartDataModel object) => [],
      toManyRelations: (PartDataModel object) => {},
      getId: (PartDataModel object) => object.id,
      setId: (PartDataModel object, int id) {
        object.id = id;
      },
      objectToFB: (PartDataModel object, fb.Builder fbb) {
        final unitOffset = fbb.writeString(object.unit);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addInt64(1, object.from);
        fbb.addInt64(2, object.to);
        fbb.addInt64(3, object.sortNumber);
        fbb.addOffset(4, unitOffset);
        fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.doneAt?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final doneAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = PartDataModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..from = const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0)
          ..to = const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
          ..sortNumber = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            10,
            0,
          )
          ..unit = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
          )
          ..doneAt = doneAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(doneAtValue);

        return object;
      },
    ),
    PersonDataModel: obx_int.EntityDefinition<PersonDataModel>(
      model: _entities[3],
      toOneRelations: (PersonDataModel object) => [],
      toManyRelations: (PersonDataModel object) => {},
      getId: (PersonDataModel object) => object.id,
      setId: (PersonDataModel object, int id) {
        object.id = id;
      },
      objectToFB: (PersonDataModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final imgPathOffset = fbb.writeString(object.imgPath);
        final contactInfoOffset = fbb.writeString(object.contactInfo);
        final phoneNumberOffset = fbb.writeString(object.phoneNumber);
        final telegramIdOffset = fbb.writeString(object.telegramId);
        final whatsAppIdOffset = fbb.writeString(object.whatsAppId);
        fbb.startTable(10);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, imgPathOffset);
        fbb.addOffset(3, contactInfoOffset);
        fbb.addOffset(4, phoneNumberOffset);
        fbb.addOffset(5, telegramIdOffset);
        fbb.addOffset(6, whatsAppIdOffset);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final imgPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final object = PersonDataModel(idParam, nameParam, imgPathParam)
          ..contactInfo = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..phoneNumber = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..telegramId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..whatsAppId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          );

        return object;
      },
    ),
    TagDataModel: obx_int.EntityDefinition<TagDataModel>(
      model: _entities[4],
      toOneRelations: (TagDataModel object) => [],
      toManyRelations: (TagDataModel object) => {},
      getId: (TagDataModel object) => object.id,
      setId: (TagDataModel object, int id) {
        object.id = id;
      },
      objectToFB: (TagDataModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final emojiOffset = fbb.writeString(object.emoji);
        final colorOffset = fbb.writeString(object.color);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, emojiOffset);
        fbb.addOffset(3, colorOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = TagDataModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..emoji = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..color = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
          );

        return object;
      },
    ),
    AudioDataModel: obx_int.EntityDefinition<AudioDataModel>(
      model: _entities[5],
      toOneRelations: (AudioDataModel object) => [
        object.host,
        object.category,
        object.tag,
      ],
      toManyRelations: (AudioDataModel object) => {
        obx_int.RelInfo<AudioDataModel>.toMany(3, object.id): object.episodes,
        obx_int.RelInfo<AudioDataModel>.toMany(4, object.id): object.allParts,
      },
      getId: (AudioDataModel object) => object.id,
      setId: (AudioDataModel object, int id) {
        object.id = id;
      },
      objectToFB: (AudioDataModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final srcLinkOffset = fbb.writeString(object.srcLink);
        final imgPathOffset = fbb.writeString(object.imgPath);
        final stateOffset = fbb.writeString(object.state);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, srcLinkOffset);
        fbb.addOffset(4, imgPathOffset);
        fbb.addOffset(5, stateOffset);
        fbb.addInt64(6, object.myStarCount);
        fbb.addInt64(7, object.starCount);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.host.targetId);
        fbb.addInt64(11, object.category.targetId);
        fbb.addInt64(12, object.tag.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = AudioDataModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..srcLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..imgPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..state = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..myStarCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..starCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
          );
        object.host.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        object.host.attach(store);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        object.category.attach(store);
        object.tag.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        object.tag.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<AudioDataModel>(
          object.episodes,
          store,
          obx_int.RelInfo<AudioDataModel>.toMany(3, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<AudioDataModel>(
          object.allParts,
          store,
          obx_int.RelInfo<AudioDataModel>.toMany(4, object.id),
        );
        return object;
      },
    ),
    BookDataModel: obx_int.EntityDefinition<BookDataModel>(
      model: _entities[6],
      toOneRelations: (BookDataModel object) => [
        object.author,
        object.lender,
        object.borrower,
        object.category,
        object.tag,
      ],
      toManyRelations: (BookDataModel object) => {
        obx_int.RelInfo<BookDataModel>.toMany(5, object.id): object.series,
        obx_int.RelInfo<BookDataModel>.toMany(6, object.id): object.allParts,
      },
      getId: (BookDataModel object) => object.id,
      setId: (BookDataModel object, int id) {
        object.id = id;
      },
      objectToFB: (BookDataModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final srcLinkOffset = fbb.writeString(object.srcLink);
        final reviewLinkOffset = fbb.writeString(object.reviewLink);
        final imgPathOffset = fbb.writeString(object.imgPath);
        final stateOffset = fbb.writeString(object.state);
        final kindOffset = fbb.writeString(object.kind);
        fbb.startTable(18);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, srcLinkOffset);
        fbb.addOffset(4, reviewLinkOffset);
        fbb.addOffset(5, imgPathOffset);
        fbb.addOffset(6, stateOffset);
        fbb.addOffset(7, kindOffset);
        fbb.addInt64(8, object.myStarCount);
        fbb.addInt64(9, object.starCount);
        fbb.addInt64(10, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(11, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(12, object.author.targetId);
        fbb.addInt64(13, object.lender.targetId);
        fbb.addInt64(14, object.borrower.targetId);
        fbb.addInt64(15, object.category.targetId);
        fbb.addInt64(16, object.tag.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = BookDataModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..srcLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..reviewLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..imgPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..state = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..kind = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..myStarCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..starCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
          );
        object.author.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        object.author.attach(store);
        object.lender.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        object.lender.attach(store);
        object.borrower.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        object.borrower.attach(store);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        object.category.attach(store);
        object.tag.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        object.tag.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<BookDataModel>(
          object.series,
          store,
          obx_int.RelInfo<BookDataModel>.toMany(5, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<BookDataModel>(
          object.allParts,
          store,
          obx_int.RelInfo<BookDataModel>.toMany(6, object.id),
        );
        return object;
      },
    ),
    ArticleDataModel: obx_int.EntityDefinition<ArticleDataModel>(
      model: _entities[7],
      toOneRelations: (ArticleDataModel object) => [
        object.writer,
        object.category,
        object.tag,
      ],
      toManyRelations: (ArticleDataModel object) => {
        obx_int.RelInfo<ArticleDataModel>.toMany(1, object.id):
            object.subArticles,
        obx_int.RelInfo<ArticleDataModel>.toMany(2, object.id): object.allParts,
      },
      getId: (ArticleDataModel object) => object.id,
      setId: (ArticleDataModel object, int id) {
        object.id = id;
      },
      objectToFB: (ArticleDataModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final srcLinkOffset = fbb.writeString(object.srcLink);
        final imgPathOffset = fbb.writeString(object.imgPath);
        final stateOffset = fbb.writeString(object.state);
        fbb.startTable(14);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, srcLinkOffset);
        fbb.addOffset(4, imgPathOffset);
        fbb.addOffset(5, stateOffset);
        fbb.addInt64(6, object.myStarCount);
        fbb.addInt64(7, object.starCount);
        fbb.addInt64(8, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.writer.targetId);
        fbb.addInt64(11, object.category.targetId);
        fbb.addInt64(12, object.tag.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = ArticleDataModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..srcLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..imgPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..state = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..myStarCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            16,
            0,
          )
          ..starCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
          );
        object.writer.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        object.writer.attach(store);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        object.category.attach(store);
        object.tag.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        object.tag.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<ArticleDataModel>(
          object.subArticles,
          store,
          obx_int.RelInfo<ArticleDataModel>.toMany(1, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<ArticleDataModel>(
          object.allParts,
          store,
          obx_int.RelInfo<ArticleDataModel>.toMany(2, object.id),
        );
        return object;
      },
    ),
    VideoDataModel: obx_int.EntityDefinition<VideoDataModel>(
      model: _entities[8],
      toOneRelations: (VideoDataModel object) => [
        object.author,
        object.category,
        object.tag,
      ],
      toManyRelations: (VideoDataModel object) => {
        obx_int.RelInfo<VideoDataModel>.toMany(7, object.id): object.seasons,
        obx_int.RelInfo<VideoDataModel>.toMany(8, object.id): object.episodes,
      },
      getId: (VideoDataModel object) => object.id,
      setId: (VideoDataModel object, int id) {
        object.id = id;
      },
      objectToFB: (VideoDataModel object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = fbb.writeString(object.description);
        final imgPathOffset = fbb.writeString(object.imgPath);
        final srcLinkOffset = fbb.writeString(object.srcLink);
        final reviewLinkOffset = fbb.writeString(object.reviewLink);
        final stateOffset = fbb.writeString(object.state);
        final kindOffset = fbb.writeString(object.kind);
        fbb.startTable(16);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, imgPathOffset);
        fbb.addOffset(4, srcLinkOffset);
        fbb.addOffset(5, reviewLinkOffset);
        fbb.addOffset(6, stateOffset);
        fbb.addOffset(7, kindOffset);
        fbb.addInt64(8, object.myStarCount);
        fbb.addInt64(9, object.starCount);
        fbb.addInt64(10, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(11, object.updatedAt.millisecondsSinceEpoch);
        fbb.addInt64(12, object.author.targetId);
        fbb.addInt64(13, object.category.targetId);
        fbb.addInt64(14, object.tag.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = VideoDataModel()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..name = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..description = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..imgPath = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..srcLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 12, '')
          ..reviewLink = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..state = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..kind = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..myStarCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..starCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            22,
            0,
          )
          ..createdAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0),
          )
          ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
            const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0),
          );
        object.author.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        object.author.attach(store);
        object.category.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        object.category.attach(store);
        object.tag.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        object.tag.attach(store);
        obx_int.InternalToManyAccess.setRelInfo<VideoDataModel>(
          object.seasons,
          store,
          obx_int.RelInfo<VideoDataModel>.toMany(7, object.id),
        );
        obx_int.InternalToManyAccess.setRelInfo<VideoDataModel>(
          object.episodes,
          store,
          obx_int.RelInfo<VideoDataModel>.toMany(8, object.id),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CategoryDataModel] entity fields to define ObjectBox queries.
class CategoryDataModel_ {
  /// See [CategoryDataModel.id].
  static final id = obx.QueryIntegerProperty<CategoryDataModel>(
    _entities[0].properties[0],
  );

  /// See [CategoryDataModel.name].
  static final name = obx.QueryStringProperty<CategoryDataModel>(
    _entities[0].properties[1],
  );

  /// See [CategoryDataModel.description].
  static final description = obx.QueryStringProperty<CategoryDataModel>(
    _entities[0].properties[2],
  );

  /// See [CategoryDataModel.imgPath].
  static final imgPath = obx.QueryStringProperty<CategoryDataModel>(
    _entities[0].properties[3],
  );

  /// See [CategoryDataModel.isFor].
  static final isFor = obx.QueryStringProperty<CategoryDataModel>(
    _entities[0].properties[4],
  );

  /// See [CategoryDataModel.isActive].
  static final isActive = obx.QueryBooleanProperty<CategoryDataModel>(
    _entities[0].properties[5],
  );

  /// See [CategoryDataModel.createdAt].
  static final createdAt = obx.QueryDateProperty<CategoryDataModel>(
    _entities[0].properties[6],
  );

  /// See [CategoryDataModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<CategoryDataModel>(
    _entities[0].properties[7],
  );
}

/// [CreatorDataModel] entity fields to define ObjectBox queries.
class CreatorDataModel_ {
  /// See [CreatorDataModel.id].
  static final id = obx.QueryIntegerProperty<CreatorDataModel>(
    _entities[1].properties[0],
  );

  /// See [CreatorDataModel.name].
  static final name = obx.QueryStringProperty<CreatorDataModel>(
    _entities[1].properties[1],
  );

  /// See [CreatorDataModel.description].
  static final description = obx.QueryStringProperty<CreatorDataModel>(
    _entities[1].properties[2],
  );

  /// See [CreatorDataModel.imgPath].
  static final imgPath = obx.QueryStringProperty<CreatorDataModel>(
    _entities[1].properties[3],
  );

  /// See [CreatorDataModel.instaLink].
  static final instaLink = obx.QueryStringProperty<CreatorDataModel>(
    _entities[1].properties[4],
  );

  /// See [CreatorDataModel.xLink].
  static final xLink = obx.QueryStringProperty<CreatorDataModel>(
    _entities[1].properties[5],
  );

  /// See [CreatorDataModel.wikiLink].
  static final wikiLink = obx.QueryStringProperty<CreatorDataModel>(
    _entities[1].properties[6],
  );

  /// See [CreatorDataModel.isFor].
  static final isFor = obx.QueryStringProperty<CreatorDataModel>(
    _entities[1].properties[7],
  );

  /// See [CreatorDataModel.createdAt].
  static final createdAt = obx.QueryDateProperty<CreatorDataModel>(
    _entities[1].properties[8],
  );

  /// See [CreatorDataModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<CreatorDataModel>(
    _entities[1].properties[9],
  );
}

/// [PartDataModel] entity fields to define ObjectBox queries.
class PartDataModel_ {
  /// See [PartDataModel.id].
  static final id = obx.QueryIntegerProperty<PartDataModel>(
    _entities[2].properties[0],
  );

  /// See [PartDataModel.from].
  static final from = obx.QueryIntegerProperty<PartDataModel>(
    _entities[2].properties[1],
  );

  /// See [PartDataModel.to].
  static final to = obx.QueryIntegerProperty<PartDataModel>(
    _entities[2].properties[2],
  );

  /// See [PartDataModel.sortNumber].
  static final sortNumber = obx.QueryIntegerProperty<PartDataModel>(
    _entities[2].properties[3],
  );

  /// See [PartDataModel.unit].
  static final unit = obx.QueryStringProperty<PartDataModel>(
    _entities[2].properties[4],
  );

  /// See [PartDataModel.createdAt].
  static final createdAt = obx.QueryDateProperty<PartDataModel>(
    _entities[2].properties[5],
  );

  /// See [PartDataModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<PartDataModel>(
    _entities[2].properties[6],
  );

  /// See [PartDataModel.doneAt].
  static final doneAt = obx.QueryDateProperty<PartDataModel>(
    _entities[2].properties[7],
  );
}

/// [PersonDataModel] entity fields to define ObjectBox queries.
class PersonDataModel_ {
  /// See [PersonDataModel.id].
  static final id = obx.QueryIntegerProperty<PersonDataModel>(
    _entities[3].properties[0],
  );

  /// See [PersonDataModel.name].
  static final name = obx.QueryStringProperty<PersonDataModel>(
    _entities[3].properties[1],
  );

  /// See [PersonDataModel.imgPath].
  static final imgPath = obx.QueryStringProperty<PersonDataModel>(
    _entities[3].properties[2],
  );

  /// See [PersonDataModel.contactInfo].
  static final contactInfo = obx.QueryStringProperty<PersonDataModel>(
    _entities[3].properties[3],
  );

  /// See [PersonDataModel.phoneNumber].
  static final phoneNumber = obx.QueryStringProperty<PersonDataModel>(
    _entities[3].properties[4],
  );

  /// See [PersonDataModel.telegramId].
  static final telegramId = obx.QueryStringProperty<PersonDataModel>(
    _entities[3].properties[5],
  );

  /// See [PersonDataModel.whatsAppId].
  static final whatsAppId = obx.QueryStringProperty<PersonDataModel>(
    _entities[3].properties[6],
  );

  /// See [PersonDataModel.createdAt].
  static final createdAt = obx.QueryDateProperty<PersonDataModel>(
    _entities[3].properties[7],
  );

  /// See [PersonDataModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<PersonDataModel>(
    _entities[3].properties[8],
  );
}

/// [TagDataModel] entity fields to define ObjectBox queries.
class TagDataModel_ {
  /// See [TagDataModel.id].
  static final id = obx.QueryIntegerProperty<TagDataModel>(
    _entities[4].properties[0],
  );

  /// See [TagDataModel.name].
  static final name = obx.QueryStringProperty<TagDataModel>(
    _entities[4].properties[1],
  );

  /// See [TagDataModel.emoji].
  static final emoji = obx.QueryStringProperty<TagDataModel>(
    _entities[4].properties[2],
  );

  /// See [TagDataModel.color].
  static final color = obx.QueryStringProperty<TagDataModel>(
    _entities[4].properties[3],
  );

  /// See [TagDataModel.createdAt].
  static final createdAt = obx.QueryDateProperty<TagDataModel>(
    _entities[4].properties[4],
  );

  /// See [TagDataModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<TagDataModel>(
    _entities[4].properties[5],
  );
}

/// [AudioDataModel] entity fields to define ObjectBox queries.
class AudioDataModel_ {
  /// See [AudioDataModel.id].
  static final id = obx.QueryIntegerProperty<AudioDataModel>(
    _entities[5].properties[0],
  );

  /// See [AudioDataModel.name].
  static final name = obx.QueryStringProperty<AudioDataModel>(
    _entities[5].properties[1],
  );

  /// See [AudioDataModel.description].
  static final description = obx.QueryStringProperty<AudioDataModel>(
    _entities[5].properties[2],
  );

  /// See [AudioDataModel.srcLink].
  static final srcLink = obx.QueryStringProperty<AudioDataModel>(
    _entities[5].properties[3],
  );

  /// See [AudioDataModel.imgPath].
  static final imgPath = obx.QueryStringProperty<AudioDataModel>(
    _entities[5].properties[4],
  );

  /// See [AudioDataModel.state].
  static final state = obx.QueryStringProperty<AudioDataModel>(
    _entities[5].properties[5],
  );

  /// See [AudioDataModel.myStarCount].
  static final myStarCount = obx.QueryIntegerProperty<AudioDataModel>(
    _entities[5].properties[6],
  );

  /// See [AudioDataModel.starCount].
  static final starCount = obx.QueryIntegerProperty<AudioDataModel>(
    _entities[5].properties[7],
  );

  /// See [AudioDataModel.createdAt].
  static final createdAt = obx.QueryDateProperty<AudioDataModel>(
    _entities[5].properties[8],
  );

  /// See [AudioDataModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<AudioDataModel>(
    _entities[5].properties[9],
  );

  /// See [AudioDataModel.host].
  static final host = obx.QueryRelationToOne<AudioDataModel, CreatorDataModel>(
    _entities[5].properties[10],
  );

  /// See [AudioDataModel.category].
  static final category =
      obx.QueryRelationToOne<AudioDataModel, CategoryDataModel>(
        _entities[5].properties[11],
      );

  /// See [AudioDataModel.tag].
  static final tag = obx.QueryRelationToOne<AudioDataModel, TagDataModel>(
    _entities[5].properties[12],
  );

  /// see [AudioDataModel.episodes]
  static final episodes =
      obx.QueryRelationToMany<AudioDataModel, AudioDataModel>(
        _entities[5].relations[0],
      );

  /// see [AudioDataModel.allParts]
  static final allParts =
      obx.QueryRelationToMany<AudioDataModel, PartDataModel>(
        _entities[5].relations[1],
      );
}

/// [BookDataModel] entity fields to define ObjectBox queries.
class BookDataModel_ {
  /// See [BookDataModel.id].
  static final id = obx.QueryIntegerProperty<BookDataModel>(
    _entities[6].properties[0],
  );

  /// See [BookDataModel.name].
  static final name = obx.QueryStringProperty<BookDataModel>(
    _entities[6].properties[1],
  );

  /// See [BookDataModel.description].
  static final description = obx.QueryStringProperty<BookDataModel>(
    _entities[6].properties[2],
  );

  /// See [BookDataModel.srcLink].
  static final srcLink = obx.QueryStringProperty<BookDataModel>(
    _entities[6].properties[3],
  );

  /// See [BookDataModel.reviewLink].
  static final reviewLink = obx.QueryStringProperty<BookDataModel>(
    _entities[6].properties[4],
  );

  /// See [BookDataModel.imgPath].
  static final imgPath = obx.QueryStringProperty<BookDataModel>(
    _entities[6].properties[5],
  );

  /// See [BookDataModel.state].
  static final state = obx.QueryStringProperty<BookDataModel>(
    _entities[6].properties[6],
  );

  /// See [BookDataModel.kind].
  static final kind = obx.QueryStringProperty<BookDataModel>(
    _entities[6].properties[7],
  );

  /// See [BookDataModel.myStarCount].
  static final myStarCount = obx.QueryIntegerProperty<BookDataModel>(
    _entities[6].properties[8],
  );

  /// See [BookDataModel.starCount].
  static final starCount = obx.QueryIntegerProperty<BookDataModel>(
    _entities[6].properties[9],
  );

  /// See [BookDataModel.createdAt].
  static final createdAt = obx.QueryDateProperty<BookDataModel>(
    _entities[6].properties[10],
  );

  /// See [BookDataModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<BookDataModel>(
    _entities[6].properties[11],
  );

  /// See [BookDataModel.author].
  static final author = obx.QueryRelationToOne<BookDataModel, CreatorDataModel>(
    _entities[6].properties[12],
  );

  /// See [BookDataModel.lender].
  static final lender = obx.QueryRelationToOne<BookDataModel, PersonDataModel>(
    _entities[6].properties[13],
  );

  /// See [BookDataModel.borrower].
  static final borrower =
      obx.QueryRelationToOne<BookDataModel, PersonDataModel>(
        _entities[6].properties[14],
      );

  /// See [BookDataModel.category].
  static final category =
      obx.QueryRelationToOne<BookDataModel, CategoryDataModel>(
        _entities[6].properties[15],
      );

  /// See [BookDataModel.tag].
  static final tag = obx.QueryRelationToOne<BookDataModel, TagDataModel>(
    _entities[6].properties[16],
  );

  /// see [BookDataModel.series]
  static final series = obx.QueryRelationToMany<BookDataModel, BookDataModel>(
    _entities[6].relations[0],
  );

  /// see [BookDataModel.allParts]
  static final allParts = obx.QueryRelationToMany<BookDataModel, PartDataModel>(
    _entities[6].relations[1],
  );
}

/// [ArticleDataModel] entity fields to define ObjectBox queries.
class ArticleDataModel_ {
  /// See [ArticleDataModel.id].
  static final id = obx.QueryIntegerProperty<ArticleDataModel>(
    _entities[7].properties[0],
  );

  /// See [ArticleDataModel.name].
  static final name = obx.QueryStringProperty<ArticleDataModel>(
    _entities[7].properties[1],
  );

  /// See [ArticleDataModel.description].
  static final description = obx.QueryStringProperty<ArticleDataModel>(
    _entities[7].properties[2],
  );

  /// See [ArticleDataModel.srcLink].
  static final srcLink = obx.QueryStringProperty<ArticleDataModel>(
    _entities[7].properties[3],
  );

  /// See [ArticleDataModel.imgPath].
  static final imgPath = obx.QueryStringProperty<ArticleDataModel>(
    _entities[7].properties[4],
  );

  /// See [ArticleDataModel.state].
  static final state = obx.QueryStringProperty<ArticleDataModel>(
    _entities[7].properties[5],
  );

  /// See [ArticleDataModel.myStarCount].
  static final myStarCount = obx.QueryIntegerProperty<ArticleDataModel>(
    _entities[7].properties[6],
  );

  /// See [ArticleDataModel.starCount].
  static final starCount = obx.QueryIntegerProperty<ArticleDataModel>(
    _entities[7].properties[7],
  );

  /// See [ArticleDataModel.createdAt].
  static final createdAt = obx.QueryDateProperty<ArticleDataModel>(
    _entities[7].properties[8],
  );

  /// See [ArticleDataModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ArticleDataModel>(
    _entities[7].properties[9],
  );

  /// See [ArticleDataModel.writer].
  static final writer =
      obx.QueryRelationToOne<ArticleDataModel, CreatorDataModel>(
        _entities[7].properties[10],
      );

  /// See [ArticleDataModel.category].
  static final category =
      obx.QueryRelationToOne<ArticleDataModel, CategoryDataModel>(
        _entities[7].properties[11],
      );

  /// See [ArticleDataModel.tag].
  static final tag = obx.QueryRelationToOne<ArticleDataModel, TagDataModel>(
    _entities[7].properties[12],
  );

  /// see [ArticleDataModel.subArticles]
  static final subArticles =
      obx.QueryRelationToMany<ArticleDataModel, ArticleDataModel>(
        _entities[7].relations[0],
      );

  /// see [ArticleDataModel.allParts]
  static final allParts =
      obx.QueryRelationToMany<ArticleDataModel, PartDataModel>(
        _entities[7].relations[1],
      );
}

/// [VideoDataModel] entity fields to define ObjectBox queries.
class VideoDataModel_ {
  /// See [VideoDataModel.id].
  static final id = obx.QueryIntegerProperty<VideoDataModel>(
    _entities[8].properties[0],
  );

  /// See [VideoDataModel.name].
  static final name = obx.QueryStringProperty<VideoDataModel>(
    _entities[8].properties[1],
  );

  /// See [VideoDataModel.description].
  static final description = obx.QueryStringProperty<VideoDataModel>(
    _entities[8].properties[2],
  );

  /// See [VideoDataModel.imgPath].
  static final imgPath = obx.QueryStringProperty<VideoDataModel>(
    _entities[8].properties[3],
  );

  /// See [VideoDataModel.srcLink].
  static final srcLink = obx.QueryStringProperty<VideoDataModel>(
    _entities[8].properties[4],
  );

  /// See [VideoDataModel.reviewLink].
  static final reviewLink = obx.QueryStringProperty<VideoDataModel>(
    _entities[8].properties[5],
  );

  /// See [VideoDataModel.state].
  static final state = obx.QueryStringProperty<VideoDataModel>(
    _entities[8].properties[6],
  );

  /// See [VideoDataModel.kind].
  static final kind = obx.QueryStringProperty<VideoDataModel>(
    _entities[8].properties[7],
  );

  /// See [VideoDataModel.myStarCount].
  static final myStarCount = obx.QueryIntegerProperty<VideoDataModel>(
    _entities[8].properties[8],
  );

  /// See [VideoDataModel.starCount].
  static final starCount = obx.QueryIntegerProperty<VideoDataModel>(
    _entities[8].properties[9],
  );

  /// See [VideoDataModel.createdAt].
  static final createdAt = obx.QueryDateProperty<VideoDataModel>(
    _entities[8].properties[10],
  );

  /// See [VideoDataModel.updatedAt].
  static final updatedAt = obx.QueryDateProperty<VideoDataModel>(
    _entities[8].properties[11],
  );

  /// See [VideoDataModel.author].
  static final author =
      obx.QueryRelationToOne<VideoDataModel, CreatorDataModel>(
        _entities[8].properties[12],
      );

  /// See [VideoDataModel.category].
  static final category =
      obx.QueryRelationToOne<VideoDataModel, CategoryDataModel>(
        _entities[8].properties[13],
      );

  /// See [VideoDataModel.tag].
  static final tag = obx.QueryRelationToOne<VideoDataModel, TagDataModel>(
    _entities[8].properties[14],
  );

  /// see [VideoDataModel.seasons]
  static final seasons =
      obx.QueryRelationToMany<VideoDataModel, VideoDataModel>(
        _entities[8].relations[0],
      );

  /// see [VideoDataModel.episodes]
  static final episodes =
      obx.QueryRelationToMany<VideoDataModel, VideoDataModel>(
        _entities[8].relations[1],
      );
}
