import 'dart:core';

class Strings {
  static const Map<String, Map<String, String>> values = {
    "fa": {
      "key": "value",
      "minAmountWarn": "مقدار باید بیشتر از صفر و ضریبی از {minAmount} باشد",
      "unitTitle": "واحد اندازه گیری",
      "itemNumTitle": "این مقدار مواد اولیه برای درست کردن چند {unitName} از این شیرینی هاست؟",
      "sellPriceTitle": "قیمتی فروش هر {unitName} از این شیرینی ها چقدره؟",
      "confirmShopItem": "تایید نهایی",
      "partnerKindError": "نوع همکاری که سفارش خرید یا فاکتور فروش دارد رو نمیشه تغییر داد.",
      "materialAmountError": "به اندازه کافی {name} برای تولید {amount} عدد {itemName} نداری",
      "itemUnitError": "واحد اندازه گیری آیتم فروشگاهی که سفارش خرید دارد رو نمیشه تغییر داد.",
      "materialUnitError": "واحد اندازه گیری ماده اولیه ای که در یک آیتم فروشگاهی استفاده شده است رو نمیشه تغییر داد.",
      "less": "کمه",
      "enough": "کافیه",
      "empty": "نداری",
      "ok": "اوکیه",
      "doneTitle": "تایید انجام",
      "doneMsg": "مطمئنی که میخوای وضعیت این سفارش رو به «انجام شده» تغییر بدی؟",
      "done": "انجام شد",
      "buyAmount": "میزان خرید",
      "sellAmount": "میزان فروش",
      "profitAmount": "میزان سود",
      "fromDate": "از تاریخ",
      "toDate": "تا تاریخ",
      "archShopTitle": "شیرینی های آرشیوی: {number} عدد",
      "archStoreTitle": "مواد اولیه آرشیوی: {number} ماده",
      "archOrderTitle": "سفارش های آرشیوی: {number} سفارش",
      "archPartnerTitle": "همکاران آرشیوی: {number} نفر",
      "archInvoiceTitle": "فاکتورهای آرشیوی: {number} فاکتور",
      "mainPage": "صفحه اصلی",
      "archivePage": "صفحه آرشیو",
      "archiveItem": "اجازه برای آرشیو",
      "editOrder": "ویرایش سفارش",
      "watchInvoice": "مشاهده فاکتور",
      "editPartner": "ویرایش همکار",
      "deleted": "حذف شده",
      "editItem": "ویرایش شیرینی",
      "thisOrder": "این سفارش",
      "deleteOrderMsg": "سفارش تمام شده رو نمیتونی پاک کنی، بهتره که آرشیوش کنی",
      "archiveOrderMsg": "فقط سفارش هایی که تمام شده اند رو میتون آرشیو کنی",
      "itemNotEnoughWarn": "آیتم های فروشگاهت برای اینکه وضعیت این سفارش رو بتونی به «انجام شد» تغییر بدی کمه",
      "order": "سفارش",
      "material": "ماده اولیه",
      "shopItem": "آیتم فروشگاه",
      "usedWarning": "از این {source} در یک یا چند {usedPlace} استفاده کردی، نمیشه پاکش یا آرشیوش کرد",
      "deleteMsg": "آیا از حذف {name} مطمئن هستی؟",
      "archiveMsg": "آیا مطئنی که میخوای {name} رو آرشیو کنی؟",
      "deleteItem": "اجازه برای حذف",
      "deleteMaterial": "حذف ماده اولیه",
      "deleteOrder": "حذف سفارش",
      "deletePartner": "حذف همکار",
      "deleteBuyInvoice": "حذف فاکتور خرید",
      "deleteSellInvoice": "حذف فاکتور فروش",
      "confirm": "آره",
      "priceOfItemList": "قیمت کل لیست",
      "profitOfItem": "سود شیرینی",
      "nameOfItem": "نام شیرینی",
      "shopItemNeedMaterial": "هر آیتم فروشگاه باید از چند ماده اولیه تشکیل شود",
      "shopItemNeedProfit": "هر آیتم فروشگاه نیاز به درصد سود دارد",
      "shopItemNeedPrice": "هر آیتم فروشگاه نیاز به مبلغ فروش دارد",
      "orderPrice": "مبلغ دریافتی",
      "deliveredDate": "تاریخ تحویل",
      "orderCreatedDate": "تاریخ ثبت",
      "buyDate": "تاریخ خرید",
      "invoiceNeedSupplier": "هر فاکتور خرید نیاز به یه تامین کننده دارد",
      "orderNeedCustomer": "هر سفارش فروش نیاز به یه مشتری دارد",
      "invoiceNeedPayedAmount": " هر فاکتور خرید نیاز به مبلغ پرداختی دارد ",
      "orderNeedPayedAmount": " هر سفارش فروش نیاز به مبلغ پرداختی دارد ",
      "invoiceNeedItems": "هر فاکتور خرید نیاز به آیتم های خریداری شده دارد",
      "orderNeedItems": "هر سفارش فروش نیاز به شیرینی های سفارش داده شده دارد",
      "repetitiveMaterial": "این ماده اولیه را قبلا وارد کرده اید",
      "in": "به",
      "noMaterialToAdd": "ماده اولیه ای که مبلغ خرید داشته باشد برای اضافه کردن وجود ندارد",
      "noItemToAdd": "در فروشگاه هیچ شیرینیی برای نمایش وجود ندارد",
      "noSupplierToAdd": "تامین کننده ای برای انتخاب ندارد",
      "noCustomerToAdd": "مشتری ای برای انتخاب ندارد",
      "enterAmountPrice": "ورود قیمت و مقدار",
      "enterAmount": "مقدار",
      "amountToAdd": "مقدار افزایش موجودی",
      "enterPrice": "قیمت",
      "emptySearchResult": "هیچ نتیجه ای برای نمایش وجود ندارد",
      "storeData": "موجودی انبار",
      "currentPrice": "قیمت فعلی",
      "emptyList": "لیست شما خالی است",
      "toman": "تومان",
      "totalPrice": "جمع کل",
      "payedPrice": "مبلغ پرداختی",
      "selectSupplier": "انتخاب تامین کننده",
      "selectCustomer": "انتخاب مشتری",
      "selectMaterial": "انتخاب مواد اولیه",
      "selectItem": "انتخاب شیرینی",
      "materialImage": "عکس ماده اولیه",
      "partnerImage": "عکس همکار",
      "invoiceImage": "عکس فاکتور خرید",
      "noBuyInvoice": "فاکتور خریدی برای نمایش وجود ندارد",
      "noOrder": "فاکتور فروشی برای نمایش وجود ندارد",
      "transactions": "تراکنش ها",
      "showOrders": "سفارشها",
      "showInvoice": "فاکتورها",
      "notEnter": "ثبت نشده",
      "addPartner": "همکار جدید",
      "mobile": "شماره همراه",
      "phone": "شماره تلفن",
      "address": "آدرس همکار",
      "kindOfPartner": "نوع همکار",
      "edit": "ویرایش",
      "active": "فعال",
      "deActive": "غیر فعال",
      "editPriceAmount": "تصحیح اطلاعات",
      "financialReport": "گزارش مالی",
      "each": "هر",
      "currentAmount": "موجودی",
      "unitPrice": "قیمت فروش",
      "basePrice": "پایه",
      "name": "نام",
      "buyInvoice": "فاکتور خرید",
      "noInvoice": "هنوز هیچ فاکتوری در سیستم ثبت نشده است",
      "noPartners": "هنوز اطلاعات همکاری در سیستم ثبت نشده است",
      "noOrders": "هنوز سفارشی در سیستم ثبت نشده است",
      "noMaterial": "هنوز ماده ی اولیه ای به انبارتان اضافه نکردید",
      "noShopItems": "هنوز محصولی به فروشگاه تان اضافه نکردید",
      "materialNeedName": "هر ماده اولیه ای نیاز به یه نام داره",
      "shopItemNeedName": "هر آیتم فروشگاه نیاز به یه نام داره",
      "partnerNeedName": "اسم همکارت رو وارد نکردی",
      "materialNeedImg": "برای این ماده اولیه عکس انتخاب نکردی",
      "partnerNeedImg": "برای همکارت عکس انتخاب نکردی",
      "entityNeedAmount": "مقدار رو وارد نکردی",
      "entityNeedPrice": "مبلغ رو وارد نکردی",
      "unit": "واحد اندازه گیری",
      "gram": "گرم",
      "liter": "لیتر",
      "miliLiter": "م لیتر",
      "kilogram": "کیلو",
      "package": "بسته",
      "piece": "دونه",
      "nameOfMaterial": "نام ماده اولیه",
      "nameOfPartner": "نام همکار",
      "hintOfMaterialName": "نام ماده اولیه را وارد کنید...",
      "addImage": "انتخاب عکس",
      "save": "ذخیره",
      "addInvoice": "فاکتور جدید",
      "addMaterial": "ماده اولیه جدید",
      "addItem": "شیرینی جدید",
      "addOrder": "سفارش جدید",
      "buy": "فاکتورهای خرید",
      "sell": "فاکتورهای فروش",
      "customer": "مشتری",
      "supplier": "تامین کننده",
      "orderSearchHint": "نام مشتری...",
      "usersSearchHint": "نام همکار...",
      "financialSearchHint": "نام همکار...",
      "itemSearchHint": "نام شیرینی...",
      "materialSearchHint": "نام ماده اولیه...",
      "all": "همه",
      "finished": "تموم ها",
      "onGoing": "مونده ها",
      "add": "افزودن",
      "shop": "فروشگاه",
      "store": "انبار",
      "orders": "سفارشها",
      "partners": "همکارها",
      "finance": "مالی",
    },
    "en": {"key": "value"},
  };

  static String get(String lang, String key) {
    return values[lang]?[key] ?? "N/A";
  }

  // use bottom function like this inject dynamic value in it

  /// String itemName = "Project A";
  ///
  /// String message = t(
  ///   "deleteDialogMessage",
  ///   params: {"item": itemName},
  /// );

  static String t(String key, {Map<String, String>? params, String locale = "en"}) {
    String value = values[locale]?[key] ?? key;

    params?.forEach((k, v) {
      value = value.replaceAll("{$k}", v);
    });

    return value;
  }
}
